## servlet configuration
server:
  port: ${PORT:8761}

## eureka server configuration
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

## application configuration
spring:
  application:
    name: ${APPLICATION_NAME:ignite-discovery-service}
  profiles:
    active: prod
