# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "production" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package spring-boot:repackage --file pom.xml
    - name: Execute Jar File
      run: sudo kill -9 `sudo lsof -t -i:8761` & sudo java -jar /home/ubuntu/actions-runner/_work/ignite_project_discovery/ignite_project_discovery/target/discovery-0.0.1-SNAPSHOT.jar &
